# Generated by Django 4.0.4 on 2022-05-31 21:22

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('galeria', '0003_location_photo_location'),
    ]

    operations = [
        migrations.RenameField(
            model_name='location',
            old_name='location',
            new_name='name',
        ),
    ]
